/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.izlozbe;

import domen.Delo;
import domen.Izlozba;
import domen.Postavka;
import forme.MeniForma;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleDela;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author hasan
 */
public class UnosIzlozbe extends javax.swing.JFrame {

    List<Delo> listaDela ;
    List<Delo> listaZaTabelu;
    /**
     * Creates new form UnosIzlozbe
     */
    public UnosIzlozbe() {
        initComponents();
        
        txtIdIzlozbe.setVisible(false);
        this.setTitle("Unos izložbe");
        
        
        listaZaTabelu = new ArrayList<>();
        srediFormu();
        this.setLocationRelativeTo(null);
        this.setResizable(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNazad = new javax.swing.JButton();
        panelPodaci = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        rbStalna = new javax.swing.JRadioButton();
        rbPrivremena = new javax.swing.JRadioButton();
        cmbSprat = new javax.swing.JComboBox();
        datDatumOd = new com.toedter.calendar.JDateChooser();
        datDatumDo = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cmbSala = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDela = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cmbDela = new javax.swing.JComboBox();
        btnDodajDelo = new javax.swing.JButton();
        btnIzbaci = new javax.swing.JButton();
        btnSacuvajPostavku = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdIzlozbe = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNazad.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnNazad.setText("<- Nazad ");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        panelPodaci.setBackground(new java.awt.Color(235, 232, 221));
        panelPodaci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel1.setText("Naziv:");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel2.setText("Tip:");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel3.setText("Datum od:");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel4.setText("Datum do:");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel5.setText("Sprat:");

        rbStalna.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        rbStalna.setText("Stalna");

        rbPrivremena.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        rbPrivremena.setText("Privremena");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel7.setText("Sala: ");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel8.setText("Opis:");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane2.setViewportView(txtOpis);

        javax.swing.GroupLayout panelPodaciLayout = new javax.swing.GroupLayout(panelPodaci);
        panelPodaci.setLayout(panelPodaciLayout);
        panelPodaciLayout.setHorizontalGroup(
            panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPodaciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPodaciLayout.createSequentialGroup()
                        .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSprat, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPodaciLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPodaciLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(44, 44, 44)))
                        .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPodaciLayout.createSequentialGroup()
                        .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(62, 62, 62)
                        .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPodaciLayout.createSequentialGroup()
                                .addComponent(rbStalna)
                                .addGap(18, 18, 18)
                                .addComponent(rbPrivremena)
                                .addGap(96, 96, 96))
                            .addComponent(txtNaziv)))
                    .addGroup(panelPodaciLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane2)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        panelPodaciLayout.setVerticalGroup(
            panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPodaciLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbStalna)
                    .addComponent(rbPrivremena))
                .addGap(21, 21, 21)
                .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPodaciLayout.createSequentialGroup()
                        .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(datDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbSprat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cmbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(datDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(panelPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(235, 232, 221));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblDela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDela);

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel6.setText("Izaberite dela za izložbu:");

        btnDodajDelo.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnDodajDelo.setText("Dodaj delo ");
        btnDodajDelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajDeloActionPerformed(evt);
            }
        });

        btnIzbaci.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnIzbaci.setText("Izbaci delo");
        btnIzbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIzbaci)
                    .addComponent(btnDodajDelo)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(cmbDela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cmbDela, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnDodajDelo)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnIzbaci)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSacuvajPostavku.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnSacuvajPostavku.setText("Sačuvaj izložbu");
        btnSacuvajPostavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajPostavkuActionPerformed(evt);
            }
        });

        jLabel10.setText("ID sačuvane izložbe: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdIzlozbe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(btnSacuvajPostavku, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnNazad)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panelPodaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addGap(42, 42, 42)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNazad)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPodaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel9)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajPostavku, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtIdIzlozbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        MeniForma mf = new MeniForma();
        mf.setUlogovaniZaposleni(Sesija.getInstanca().getZaposleni());
        mf.srediIzgled();
        mf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnSacuvajPostavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajPostavkuActionPerformed
        String naziv = txtNaziv.getText().trim();
        String tip = "";
        if(rbPrivremena.isSelected()){
            tip = "privremena";
        }else if(rbStalna.isSelected()){
            tip = "stalna";
        }
     
    
        
     //   SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datOd = datDatumOd.getDate();
        Date datDo = datDatumDo.getDate();
        int sprat = (int) cmbSprat.getSelectedItem();
        int sala = (int) cmbSala.getSelectedItem();
        String opis = txtOpis.getText().trim();
        
        
        
        String poruka = "Izložba nije sačuvana!\n";
        
        if(naziv.isEmpty() || tip == "" || sprat == 0 || sala == 0 || opis.isEmpty()){
            JOptionPane.showMessageDialog(this, poruka+"Sva polja su obavezna.");
            return;
        }
        if (tip == "privremena") {
            if (!datOd.before(datDo)) {
                JOptionPane.showMessageDialog(this, poruka + "Polje datum do mora da bude nakon polja datum od.");
                return;

            }
        }
        if (tip == "stalna") {
            datOd = null;
            datDo = null;
        }
        ModelTabeleDela mtd = (ModelTabeleDela) tblDela.getModel();
            List<Delo> lista = mtd.getLista();
            if(lista.isEmpty()){
                JOptionPane.showMessageDialog(this, poruka+"Morate da ubacite bar jedno delo u tabelu.");
                return;
            }else{
                Izlozba izlozba = new Izlozba(-1, naziv, tip, datOd, datDo);
                ArrayList<Postavka> listaPostavki = new ArrayList<>();
                 for (Delo delo : lista) {
                    Postavka p = new Postavka();
                    p.setIzlozba(izlozba);
                    p.setDelo(delo);
                    p.setOpis(opis);
                    p.setSala(sala);
                    p.setSprat(sprat);
                    listaPostavki.add(p);
                 }
                 izlozba.setListaPostavki(listaPostavki);
                 
              /*  Izlozba izlozba = new Izlozba(-1, naziv, tip, datOd, datDo);
                ServerskiOdgovor so = Kontroler.getInstanca().vratiIzlozbaID(izlozba);
                if(so!=null && so.getParametar()!=null){
              //  int nizID[] = new int[tblDela.getRowCount()];
                    Izlozba i = (Izlozba) so.getParametar();
                    int idIzBaze = i.getIzlozbaID();
                    System.out.println("ID izlozbe u bazi: "+idIzBaze);
                for (Delo delo : lista) {
                    Postavka p = new Postavka();
                    p.setIzlozba(i);
                    p.setDelo(delo);
                    p.setOpis(opis);
                    p.setSala(sala);
                    p.setSprat(sprat);
                    listaPostavki.add(p);
                }*/
                 ServerskiOdgovor so2 = Kontroler.getInstanca().kreirajIzlozbu(izlozba);
                
                if(so2!=null && so2.isUspesno()){
                    Izlozba i = (Izlozba) so2.getParametar();
                    txtIdIzlozbe.setText(i.getIzlozbaID() + "");
                    txtIdIzlozbe.setEditable(false);
                    JOptionPane.showMessageDialog(this, "Izložba je sačuvana!");
                    txtIdIzlozbe.setVisible(true);

               
                }else{
                     JOptionPane.showMessageDialog(this, poruka);
                     System.out.println("Neuspelo čuvanje izložbe.");
                   
                }
            /*}else{
                    JOptionPane.showMessageDialog(this, poruka);
                    System.out.println("Izlozba nije uspesno sacuvana.");
  
                }*/
            }
            
        
        
        
               
    }//GEN-LAST:event_btnSacuvajPostavkuActionPerformed

    private void btnDodajDeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajDeloActionPerformed
        Delo delo = (Delo) cmbDela.getSelectedItem();
        int odabranoDelo = cmbDela.getSelectedIndex();
        if(odabranoDelo == 0 || odabranoDelo == -1){
            System.out.println("Izaberi bar jedno");
            JOptionPane.showMessageDialog(this, "Morate da izaberete bar jedno delo.");
        }else{
            if(!listaZaTabelu.contains(delo)){
                listaZaTabelu.add(delo);
                ModelTabeleDela mtd = new ModelTabeleDela(listaZaTabelu);
                tblDela.setModel(mtd);
            }
            else{
                JOptionPane.showMessageDialog(this, "Već ste ubacili izabrano delo.");
            }
        }
    }//GEN-LAST:event_btnDodajDeloActionPerformed

    private void btnIzbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciActionPerformed
        int red = tblDela.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this,"Neuspešno izbacivanje!\nNiste izabrali nijedno delo iz tabele");
            return;
        }
        ModelTabeleDela mtd = (ModelTabeleDela) tblDela.getModel();
        mtd.izbaciDelo(red);
        
    }//GEN-LAST:event_btnIzbaciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosIzlozbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosIzlozbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosIzlozbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosIzlozbe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosIzlozbe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajDelo;
    private javax.swing.JButton btnIzbaci;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnSacuvajPostavku;
    private javax.swing.JComboBox cmbDela;
    private javax.swing.JComboBox cmbSala;
    private javax.swing.JComboBox cmbSprat;
    private com.toedter.calendar.JDateChooser datDatumDo;
    private com.toedter.calendar.JDateChooser datDatumOd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelPodaci;
    private javax.swing.JRadioButton rbPrivremena;
    private javax.swing.JRadioButton rbStalna;
    private javax.swing.JTable tblDela;
    private javax.swing.JTextField txtIdIzlozbe;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        cmbSprat.removeAllItems();
        for (int i = 1; i < 4; i++) {
            cmbSprat.addItem(i);

        }
        cmbSala.removeAllItems();
        for (int i = 1; i < 7; i++) {
           cmbSala.addItem(i);
        }
        srediButtonGroup();
        srediTabelu(listaZaTabelu);
        popuniCmbDela();
        srediZaListener();
       
        
    }

    private void srediButtonGroup() {
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbStalna);
        bg.add(rbPrivremena);
    }

    private void srediTabelu(List<Delo> lista) {
        ModelTabeleDela mtd = new ModelTabeleDela(lista);
        tblDela.setFont(new Font("Lucida Bright", Font.PLAIN, 14));
        tblDela.getTableHeader().setFont(new Font("Lucida Bright", Font.PLAIN, 14));
        tblDela.setModel(mtd);
    }

    private void popuniCmbDela() {
        ServerskiOdgovor so = Kontroler.getInstanca().vratiListuDela(new Delo(-1, "", "", ""));
        if(so!=null){
        listaDela = (List<Delo>) so.getParametar();
        cmbDela.removeAllItems();
        cmbDela.insertItemAt(null, 0);
        for (Delo delo : listaDela) {
            cmbDela.addItem(delo);
        }
        
        System.out.println("Sistem je vratio listu dela.");
        }
        else {
            JOptionPane.showMessageDialog(this, "Neuspešno učitana lista dela. Pokušajte kasnije");
            btnSacuvajPostavku.setEnabled(false);
            return;
        }
    }

    private void srediZaListener() {
        rbPrivremena.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                datDatumDo.setEnabled(true);
                datDatumOd.setEnabled(true);
            }
        });
        rbStalna.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                datDatumDo.setEnabled(false);
                datDatumOd.setEnabled(false);
            }
        });
    }
}
