/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.vodici;

import domen.Izlozba;
import domen.Vodic;
import forme.MeniForma;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleVodici;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author hasan
 */
public class PretragaVodica extends javax.swing.JFrame {

    
    List<Vodic> listaSvihVodica;
    List<Vodic> listaSaKriterijumom;
    String porukaPoz = "Vodiči su pronađeni!\n";
    String porukaNeg = "Vodiči nisu pronađeni!\n";
    
    /**
     * Creates new form PretragaVodica
     */
    public PretragaVodica() {
        initComponents();
        this.setTitle("Pretraga vodiča");
        
        srediFormu();
        this.setLocationRelativeTo(null);
        this.setResizable(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNazad = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbIzlozbe = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        datAngazovanja = new com.toedter.calendar.JDateChooser();
        btnPretraziIzlozba = new javax.swing.JButton();
        btnPretraziDatum = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVodici = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNazad.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnNazad.setText("<- Nazad ");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(235, 232, 221));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel1.setText("Izložba:");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel2.setText("Angažovani vodič dana :");

        btnPretraziIzlozba.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnPretraziIzlozba.setText("Pretraži");
        btnPretraziIzlozba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziIzlozbaActionPerformed(evt);
            }
        });

        btnPretraziDatum.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnPretraziDatum.setText("Pretraži");
        btnPretraziDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziDatumActionPerformed(evt);
            }
        });

        tblVodici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVodici);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbIzlozbe, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datAngazovanja, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPretraziIzlozba, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPretraziDatum, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbIzlozbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziIzlozba))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(datAngazovanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPretraziDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNazad)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNazad)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        MeniForma mf = new MeniForma();
        mf.setUlogovaniZaposleni(Sesija.getInstanca().getZaposleni());
        mf.srediIzgled();
        mf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnPretraziDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziDatumActionPerformed
         Date datum = datAngazovanja.getDate();
         if(datum == null){
            JOptionPane.showMessageDialog(this, "Morate da izaberete datum!");
            return;
         }
        Vodic vodic = new Vodic(-1, "", datum, -1);
        listaSaKriterijumom = new ArrayList<>();
        ServerskiOdgovor so = Kontroler.getInstanca().nadjiVodice(vodic);
        if (so != null && so.getParametar() != null) {
            ModelTabeleVodici mtv = (ModelTabeleVodici) tblVodici.getModel();
            mtv.isprazniListu();
            listaSaKriterijumom = (List<Vodic>) so.getParametar();
            mtv.setLista(listaSaKriterijumom);
            if (listaSaKriterijumom.size() == 0) {
                JOptionPane.showMessageDialog(this, porukaNeg + "Ne postoje vodiči koji su angažovani tog dana.");
                return;
            } else {
                JOptionPane.showMessageDialog(this, porukaPoz);

            }
        }else{
            JOptionPane.showMessageDialog(this,porukaNeg);
            btnPretraziDatum.setEnabled(false);
            btnPretraziIzlozba.setEnabled(false);
            
        }
         
    }//GEN-LAST:event_btnPretraziDatumActionPerformed

    private void btnPretraziIzlozbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziIzlozbaActionPerformed
        Izlozba izlozba = (Izlozba) cmbIzlozbe.getSelectedItem();
        if (izlozba == null) {
            JOptionPane.showMessageDialog(this, "Morate prvo da izaberete izlozbu!");
            return;
        }
    
        int izlozbaID = izlozba.getIzlozbaID();
        listaSaKriterijumom = new ArrayList<>();
        Vodic v = new Vodic(-1, "", null, izlozbaID);
        ServerskiOdgovor so = Kontroler.getInstanca().nadjiVodice(v);
        if(so != null && so.getParametar()!=null){
            ModelTabeleVodici mtv = (ModelTabeleVodici) tblVodici.getModel();
            mtv.isprazniListu();
            listaSaKriterijumom = (List<Vodic>) so.getParametar();
            mtv.setLista(listaSaKriterijumom);
            if(listaSaKriterijumom.size() == 0){
                JOptionPane.showMessageDialog(this,porukaNeg+"Ne postoje vodiči koji se nalaze na izabranoj izložbi.");
                return;
            }else{
                JOptionPane.showMessageDialog(this,porukaPoz);

            }
        }else{
            JOptionPane.showMessageDialog(this, porukaNeg);
            btnPretraziDatum.setEnabled(false);
            btnPretraziIzlozba.setEnabled(false);
        }
    }//GEN-LAST:event_btnPretraziIzlozbaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaVodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaVodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaVodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaVodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaVodica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnPretraziDatum;
    private javax.swing.JButton btnPretraziIzlozba;
    private javax.swing.JComboBox cmbIzlozbe;
    private com.toedter.calendar.JDateChooser datAngazovanja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVodici;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        
        popuniCmbIzlozbe();
        
        listaSvihVodica = new ArrayList<>();
        ModelTabeleVodici mtv = new ModelTabeleVodici();
        tblVodici.setModel(mtv);
        Vodic vodic = new Vodic(-1, "", null, -1);
        ServerskiOdgovor so = Kontroler.getInstanca().vratiListuVodica(vodic);
        listaSvihVodica = (List<Vodic>) so.getParametar();
        if(so!=null && listaSvihVodica!=null){
            mtv.setLista(listaSvihVodica);
        }else{
            JOptionPane.showMessageDialog(this,"Greska u ucitavanju liste");
            btnPretraziDatum.setEnabled(false);
            btnPretraziIzlozba.setEnabled(false);
        }
    }

    private void popuniCmbIzlozbe() {
        List<Izlozba> listaIzlozbi= new ArrayList<>();
        Izlozba izlozba = new Izlozba(-1, "", "", null, null);
        ServerskiOdgovor so = Kontroler.getInstanca().vratiListuIzlozbi(izlozba);
        if (so != null && so.getParametar()!=null) {
            listaIzlozbi = (List<Izlozba>) so.getParametar();
            cmbIzlozbe.removeAllItems();
            cmbIzlozbe.insertItemAt(null, 0);
            for (Izlozba i : listaIzlozbi) {
                cmbIzlozbe.addItem(i);
            }

            System.out.println("Sistem je vratio listu izlozbi.");
        } else {
            JOptionPane.showMessageDialog(this, "Neuspešno učitana lista izlozbi. Pokušajte kasnije");
            return;
        }
    }
}
