/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Zaposleni;
import forme.clanskeKarte.ObnavljanjeClanskeKarte;
import forme.clanskeKarte.UnosClanskeKarte;
import forme.izlozbe.PretragaIzlozbe;
import forme.izlozbe.UnosIzlozbe;
import forme.ulaznice.KreiranjeUlaznice;
import forme.vodici.PretragaVodica;
import forme.vodici.UnosVodica;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author hasan
 */
public class MeniForma extends javax.swing.JFrame {

    Zaposleni ulogovaniZaposleni;

    public Zaposleni getUlogovaniZaposleni() {
        return ulogovaniZaposleni;
    }

    public void setUlogovaniZaposleni(Zaposleni ulogovaniZaposleni) {
        this.ulogovaniZaposleni = ulogovaniZaposleni;
    }
    
    
    /**
     * Creates new form MeniForma
     */
    public MeniForma() {
        initComponents();
        this.setTitle("Glavni meni");
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUlogovaniZaposleni = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSlika = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        miUlaznice = new javax.swing.JMenu();
        mKreiranjeUlaznice = new javax.swing.JMenuItem();
        miClanskaKarta = new javax.swing.JMenu();
        mUnosClanskeKarte = new javax.swing.JMenuItem();
        mObnavljanjeClanskeKarte = new javax.swing.JMenuItem();
        miIzlozbe = new javax.swing.JMenu();
        mUnosIzlozbe = new javax.swing.JMenuItem();
        mPretragaIzlozbe = new javax.swing.JMenuItem();
        mPretragaVodica = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 232, 221));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel1.setText("Zaposleni:");

        txtUlogovaniZaposleni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dobrodošli u Narodni Muzej u Beogradu!");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblSlika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUlogovaniZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(69, 69, 69)
                        .addComponent(lblSlika))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2)))
                .addGap(0, 143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUlogovaniZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        miUlaznice.setText("Ulaznice");
        miUlaznice.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        mKreiranjeUlaznice.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        mKreiranjeUlaznice.setText("Kreiranje ulaznice");
        mKreiranjeUlaznice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKreiranjeUlazniceActionPerformed(evt);
            }
        });
        miUlaznice.add(mKreiranjeUlaznice);

        jMenuBar1.add(miUlaznice);

        miClanskaKarta.setText("Članska karta");
        miClanskaKarta.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        mUnosClanskeKarte.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        mUnosClanskeKarte.setText("Unos članske karte");
        mUnosClanskeKarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUnosClanskeKarteActionPerformed(evt);
            }
        });
        miClanskaKarta.add(mUnosClanskeKarte);

        mObnavljanjeClanskeKarte.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        mObnavljanjeClanskeKarte.setText("Obnavljanje članske karte");
        mObnavljanjeClanskeKarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mObnavljanjeClanskeKarteActionPerformed(evt);
            }
        });
        miClanskaKarta.add(mObnavljanjeClanskeKarte);

        jMenuBar1.add(miClanskaKarta);

        miIzlozbe.setText("Izložbe");
        miIzlozbe.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        mUnosIzlozbe.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        mUnosIzlozbe.setText("Unos izložbe");
        mUnosIzlozbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUnosIzlozbeActionPerformed(evt);
            }
        });
        miIzlozbe.add(mUnosIzlozbe);

        mPretragaIzlozbe.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        mPretragaIzlozbe.setText("Pretraga izložbe");
        mPretragaIzlozbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPretragaIzlozbeActionPerformed(evt);
            }
        });
        miIzlozbe.add(mPretragaIzlozbe);

        jMenuBar1.add(miIzlozbe);

        mPretragaVodica.setText("Vodiči");
        mPretragaVodica.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        jMenuItem3.setText("Unos vodiča");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mPretragaVodica.add(jMenuItem3);

        jMenuItem5.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        jMenuItem5.setText("Pretraga vodiča");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mPretragaVodica.add(jMenuItem5);

        jMenuBar1.add(mPretragaVodica);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mObnavljanjeClanskeKarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mObnavljanjeClanskeKarteActionPerformed
        ObnavljanjeClanskeKarte ock = new ObnavljanjeClanskeKarte();
        this.setVisible(false);
        ock.setVisible(true);
    }//GEN-LAST:event_mObnavljanjeClanskeKarteActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        PretragaVodica pv = new PretragaVodica();
        this.setVisible(false);
        pv.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mKreiranjeUlazniceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKreiranjeUlazniceActionPerformed
        KreiranjeUlaznice kz = new KreiranjeUlaznice();
        this.setVisible(false);
        kz.setVisible(true);
    }//GEN-LAST:event_mKreiranjeUlazniceActionPerformed

    private void mUnosClanskeKarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUnosClanskeKarteActionPerformed
        UnosClanskeKarte uck = new UnosClanskeKarte();
        this.setVisible(false);
        uck.setVisible(true);
    }//GEN-LAST:event_mUnosClanskeKarteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        UnosVodica uv = new UnosVodica();
        this.setVisible(false);
        uv.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mUnosIzlozbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUnosIzlozbeActionPerformed
        UnosIzlozbe ui = new UnosIzlozbe();
        this.setVisible(false);
        ui.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mUnosIzlozbeActionPerformed

    private void mPretragaIzlozbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPretragaIzlozbeActionPerformed
        PretragaIzlozbe pi = new PretragaIzlozbe();
        this.setVisible(false);
        pi.setVisible(true);
    }//GEN-LAST:event_mPretragaIzlozbeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeniForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeniForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeniForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeniForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeniForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JMenuItem mKreiranjeUlaznice;
    private javax.swing.JMenuItem mObnavljanjeClanskeKarte;
    private javax.swing.JMenuItem mPretragaIzlozbe;
    private javax.swing.JMenu mPretragaVodica;
    private javax.swing.JMenuItem mUnosClanskeKarte;
    private javax.swing.JMenuItem mUnosIzlozbe;
    private javax.swing.JMenu miClanskaKarta;
    private javax.swing.JMenu miIzlozbe;
    private javax.swing.JMenu miUlaznice;
    private javax.swing.JLabel txtUlogovaniZaposleni;
    // End of variables declaration//GEN-END:variables

    public void srediIzgled() {
        txtUlogovaniZaposleni.setText(ulogovaniZaposleni.toString());
        txtUlogovaniZaposleni.setFont(new Font("Lucida Bright", Font.PLAIN, 14));
    }
    

}
