/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.ulaznice;

import domen.Izlozba;
import domen.Ulaznica;
import domen.Zaposleni;
import forme.MeniForma;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import sesija.Sesija;
import transfer.ServerskiOdgovor;

/**
 *
 * @author hasan
 */
public class KreiranjeUlaznice extends javax.swing.JFrame {

    List<Izlozba> listaIzlozbi;
    SimpleDateFormat sdf;
    /**
     * Creates new form KreiranjeUlaznice
     */
    public KreiranjeUlaznice() {
        initComponents();
        sdf = new SimpleDateFormat("dd.MM.yyyy");

        srediFormu();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        btnNazad = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbIzlozbe = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCena = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rbDa = new javax.swing.JRadioButton();
        rbNe = new javax.swing.JRadioButton();
        lblCena = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNazad.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnNazad.setText("<- Nazad ");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(235, 232, 221));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel1.setText("Izaberi izlozbe: ");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel2.setText("Datum: ");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel3.setText("Cena:");

        lblDatum.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel4.setText("din");

        btnCena.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnCena.setText("Izračunaj cenu");
        btnCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCenaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel5.setText("Članska karta:");

        rbDa.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        rbDa.setText("Da");

        rbNe.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        rbNe.setText("Ne");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbDa)
                                .addGap(18, 18, 18)
                                .addComponent(rbNe))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbIzlozbe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCena)
                                        .addComponent(lblCena, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 27, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbIzlozbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDatum))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbDa)
                    .addComponent(rbNe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnCena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCena)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnSacuvaj.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        btnSacuvaj.setText("Kreiraj ulaznicu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvaj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnNazad)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNazad)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSacuvaj)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        MeniForma mf = new MeniForma();
        mf.setUlogovaniZaposleni(Sesija.getInstanca().getZaposleni());
        mf.srediIzgled();
        mf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenaActionPerformed
        Date dat = new Date();
        Calendar kal =  Calendar.getInstance();
        kal.setTime(dat);
        int dan = kal.get(Calendar.DAY_OF_WEEK);
        System.out.println(dan);
                
        if(rbDa.isSelected() || dan == 7){
             txtCena.setText("0.00");
             lblCena.setText("Karta je besplatna.");
        }
        if(cmbIzlozbe.getSelectedItem() != null && rbNe.isSelected()){
             txtCena.setText("300.00");
             lblCena.setText("");
        }
        if(cmbIzlozbe.getSelectedItem() != null && rbDa.isSelected()){
           txtCena.setText("0.00");
           lblCena.setText("Karta je besplatna.");
        }
        if(cmbIzlozbe.getSelectedItem() == null && rbNe.isSelected()){
           txtCena.setText("");
           lblCena.setText("");
        }
        if(!rbDa.isSelected() && !rbNe.isSelected() && cmbIzlozbe.getSelectedItem() == null)     {
            JOptionPane.showMessageDialog(this, "Morate da popunite bar neko polje iz forme za računanje cene.");
            return;
        }
    }//GEN-LAST:event_btnCenaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        Izlozba izlozba = (Izlozba) cmbIzlozbe.getSelectedItem();
        Date datum = new Date();
        Double cena = 0.00;
        if (!txtCena.getText().isEmpty()) {
            cena = Double.parseDouble(txtCena.getText().trim());
        }else{
            JOptionPane.showMessageDialog(this, "Morate prvo cenu da izračunate.");
            return;
        }
        if (datum != null && izlozba != null) {
            Zaposleni z = Sesija.getInstanca().getZaposleni();
            Ulaznica ulaznica = new Ulaznica(-1, datum, cena, z, izlozba);
            ServerskiOdgovor so = Kontroler.getInstanca().kreirajUlaznicu(ulaznica);
            if (so != null && so.isUspesno()) {
                JOptionPane.showMessageDialog(this, "Sistem je kreirao ulaznicu.");
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne može da kreira ulaznicu.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja.");
            return;
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreiranjeUlaznice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreiranjeUlaznice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreiranjeUlaznice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreiranjeUlaznice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KreiranjeUlaznice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCena;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmbIzlozbe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JRadioButton rbDa;
    private javax.swing.JRadioButton rbNe;
    private javax.swing.JTextField txtCena;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        
        this.setTitle("Kreiranje ulaznice");
        popuniCmbIzlozbe();
        
        Date dat = new Date();
        String datum = sdf.format(dat);
        System.out.println(datum);
        lblDatum.setText(datum);
        
        buttonGroup2.add(rbDa);
        buttonGroup2.add(rbNe);
        
        txtCena.setEnabled(false);
        
    }

    private void popuniCmbIzlozbe() {
        listaIzlozbi = new ArrayList<>();
        Izlozba izlozba = new Izlozba(-1, "", "", null, null);
        ServerskiOdgovor so = Kontroler.getInstanca().vratiListuIzlozbi(izlozba);
        if (so != null && so.getParametar()!=null) {
            listaIzlozbi = (List<Izlozba>) so.getParametar();
            cmbIzlozbe.removeAllItems();
            cmbIzlozbe.insertItemAt(null, 0);
            for (Izlozba i : listaIzlozbi) {
                cmbIzlozbe.addItem(i);
            }

            System.out.println("Sistem je vratio listu izlozbi.");
        } else {
            JOptionPane.showMessageDialog(this, "Neuspešno učitana lista izložbi. Pokušajte kasnije.");
            btnSacuvaj.setEnabled(false);
            return;
        }
    }
}
